
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  SuggestExtensions: false

Metrics/BlockLength:
  # Ignore the block lengths in these files as they are based on long blocks.
  Exclude:
    - 'Rakefile'
    - '*.gemspec'
    - '**/*.rake'
    - 'test/**/*.rb'

Metrics/ClassLength:
  # Ignore the block lengths in these files as they are based on long blocks.
  Exclude:
    - 'test/**/*.rb'
